apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "artifactory-ha.node.name" . }}
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    component: {{ .Values.artifactory.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "artifactory-ha.node.name" . }}
  replicas: {{ .Values.artifactory.node.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "artifactory-ha.name" . }}
      role: {{ template "artifactory-ha.node.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "artifactory-ha.name" . }}
        chart: {{ template "artifactory-ha.chart" . }}
        role: {{ template "artifactory-ha.node.name" . }}
        heritage: {{ .Release.Service }}
        component: {{ .Values.artifactory.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/binarystore: {{ include (print $.Template.BasePath "/artifactory-binarystore-secret.yaml") . | sha256sum }}
        checksum/systemyaml: {{ include (print $.Template.BasePath "/artifactory-system-yaml.yaml") . | sha256sum }}
      {{- range $key, $value := .Values.artifactory.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "artifactory-ha.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.artifactory.terminationGracePeriodSeconds }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      securityContext:
        runAsUser: {{ .Values.artifactory.uid }}
        fsGroup: {{ .Values.artifactory.uid }}
      initContainers:
  {{- if .Values.artifactory.persistence.enabled }}
    {{- if eq .Values.artifactory.persistence.type "file-system" }}
      {{- if .Values.artifactory.persistence.fileSystem.existingSharedClaim.enabled }}
      - name: "create-artifactory-data-dir"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: {{ .Values.artifactory.image.pullPolicy }}
        command:
        - 'sh'
        - '-c'
        - >
          mkdir {{ .Values.artifactory.persistence.fileSystem.existingSharedClaim.dataDir }}
        volumeMounts:
        - mountPath: {{ .Values.artifactory.persistence.mountPath | quote }}
          name: volume
      {{- end }}
    {{- end }}
      {{- if .Values.artifactory.deleteDBPropertiesOnStartup }}
      - name: "delete-db-properties"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: {{ .Values.artifactory.image.pullPolicy }}
        command:
          - 'sh'
          - '-c'
          - 'rm -fv {{ .Values.artifactory.persistence.mountPath }}/etc/db.properties'
        volumeMounts:
          - mountPath: {{ .Values.artifactory.persistence.mountPath | quote }}
            name: volume
      {{- end }}
      - name: "remove-lost-found"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: {{ .Values.artifactory.image.pullPolicy }}
        command:
        - 'sh'
        - '-c'
        - >
          rm -rfv {{ .Values.artifactory.persistence.mountPath }}/lost+found
        volumeMounts:
        - mountPath: {{ .Values.artifactory.persistence.mountPath | quote }}
          name: volume
    {{- end }}
      - name: 'copy-system-yaml'
        image: '{{ .Values.initContainerImage }}'
        command:
        - '/bin/sh'
        - '-c'
        - >
          echo "Sleeping to allow time for primary node to come up";
          sleep 60;
          echo "Copy system.yaml to {{ .Values.artifactory.persistence.mountPath }}/etc";
          mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc;
          mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc/access/keys/trusted;
          cp -fv /tmp/etc/system.yaml {{ .Values.artifactory.persistence.mountPath }}/etc/system.yaml;
          echo "Remove {{ .Values.artifactory.persistence.mountPath }}/lost+found folder if exists";
          rm -rfv {{ .Values.artifactory.persistence.mountPath }}/lost+found;
        volumeMounts:
        - name: volume
          mountPath: {{ .Values.artifactory.persistence.mountPath | quote }}
        - name: systemyaml
          mountPath: "/tmp/etc/system.yaml"
          subPath: system.yaml
    {{- if .Values.artifactory.customPersistentPodVolumeClaim }}
      - name: "prepare-custom-persistent-volume"
        image: "{{ .Values.initContainerImage }}"
        command:
          - 'sh'
          - '-c'
          - >
            chown -Rv {{ .Values.artifactory.uid }}:{{ .Values.artifactory.uid }} {{ .Values.artifactory.customPersistentPodVolumeClaim.mountPath }}
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: {{ .Values.artifactory.customPersistentPodVolumeClaim.name }}
            mountPath: {{ .Values.artifactory.customPersistentPodVolumeClaim.mountPath }}
    {{- end }}
      {{- if or .Values.postgresql.enabled ( and .Values.database.host .Values.database.port ) }}
      - name: "wait-for-db"
        image: "{{ .Values.initContainerImage }}"
        command:
        - 'sh'
        - '-c'
        - >
      {{- if .Values.postgresql.enabled }}
          until nc -z -w 2 {{ .Release.Name }}-postgresql {{ .Values.postgresql.service.port }} && echo database ok; do
      {{- else }}
        {{- if and .Values.database.host .Values.database.port }}
          until nc -z -w 2 {{ .Values.database.host }} {{ .Values.database.port }} && echo database ok; do
        {{- else }}
          until true; do
        {{- end }}
      {{- end }}
            sleep 2;
          done;
      {{- end }}
    {{- if .Values.artifactory.customInitContainers }}
{{ tpl .Values.artifactory.customInitContainers . | indent 6 }}
    {{- end }}
      containers:
      - name: {{ .Values.artifactory.name }}
        image: '{{ .Values.artifactory.image.repository }}:{{ default .Chart.AppVersion .Values.artifactory.image.version }}'
        imagePullPolicy: {{ .Values.artifactory.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
      {{- if .Values.artifactory.preStartCommand }}
        command:
        - '/bin/sh'
        - '-c'
        - >
          {{- if .Values.artifactory.userPluginSecrets }}
          echo "Copying plugins";
          cp -Lrf /tmp/plugin/*/* /tmp/plugins;
          {{- end }}
          echo "Running custom preStartCommand command";
          {{ .Values.artifactory.preStartCommand }};
          /entrypoint-artifactory.sh
      {{- end }}
      {{- if .Values.artifactory.postStartCommand }}
        lifecycle:
          postStart:
            exec:
              command:
              - '/bin/sh'
              - '-c'
              - >
                {{ .Values.artifactory.postStartCommand }}
      {{- end }}
        env:
        - name: JF_SHARED_NODE_PRIMARY
          value: "false"
      {{- range .Values.artifactory.extraEnvironmentVariables }}
        - name: {{ .name }}
          value: '{{ tpl .value $ }}'
      {{- end }}
        ports:
        - containerPort: {{ .Values.artifactory.internalPort }}
        {{- if .Values.artifactory.node.javaOpts.jmx.enabled }}
        - containerPort: {{ .Values.artifactory.node.javaOpts.jmx.port }}
        {{- end }}
        volumeMounts:
       {{- if .Values.artifactory.customPersistentVolumeClaim }}
        - name: {{ .Values.artifactory.customPersistentVolumeClaim.name }}
          mountPath: {{ .Values.artifactory.customPersistentVolumeClaim.mountPath }}
       {{- end }}
        {{- if .Values.artifactory.customPersistentPodVolumeClaim }}
        - name: {{ .Values.artifactory.customPersistentPodVolumeClaim.name }}
          mountPath: {{ .Values.artifactory.customPersistentPodVolumeClaim.mountPath }}
        {{- end }}
      {{- if .Values.artifactory.userPluginSecrets }}
        - name: tmp-plugins
          mountPath: "/tmp/plugins/"
      {{- range .Values.artifactory.userPluginSecrets }}
        - name: {{ tpl . $ }}
          mountPath: "/tmp/plugin/{{ tpl . $ }}"
      {{- end }}
      {{- end }}
        - name: volume
          mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
      {{- if eq .Values.artifactory.persistence.type "file-system" }}
        {{- if .Values.artifactory.persistence.fileSystem.existingSharedClaim.enabled }}
          {{- range $sharedClaimNumber, $e := until (.Values.artifactory.persistence.fileSystem.existingSharedClaim.numberOfExistingClaims|int) }}
        - name: artifactory-ha-data-{{ $sharedClaimNumber }}
          mountPath: "{{ $.Values.artifactory.persistence.fileSystem.existingSharedClaim.dataDir }}/filestore{{ $sharedClaimNumber }}"
          {{- end }}
        - name: artifactory-ha-backup
          mountPath: "{{ $.Values.artifactory.persistence.fileSystem.existingSharedClaim.backupDir }}"
        {{- end }}
      {{- end }}
      {{- if eq .Values.artifactory.persistence.type "nfs" }}
        - name: artifactory-ha-data
          mountPath: "{{ .Values.artifactory.persistence.nfs.dataDir }}"
        - name: artifactory-ha-backup
          mountPath: "{{ .Values.artifactory.persistence.nfs.backupDir }}"
      {{- else }}
      {{- if .Values.artifactory.binarystore.enabled }}
        - name: binarystore-xml
          mountPath: "/artifactory_extra_conf/binarystore.xml"
          subPath: binarystore.xml
      {{- end }}
      {{- end }}
      {{- if .Values.artifactory.replicator.enabled }}
        - name: replicator-config
          mountPath: "/replicator_extra_conf/replicator.yaml"
          subPath: replicator.yaml
      {{- end }}
        - name: installer-info
          mountPath: "/artifactory_extra_conf/info/installer-info.json"
          subPath: installer-info.json
      {{- if .Values.artifactory.customVolumeMounts }}
{{ tpl .Values.artifactory.customVolumeMounts . | indent 8 }}
      {{- end }}
        resources:
{{ toYaml .Values.artifactory.node.resources | indent 10 }}
        {{- if .Values.artifactory.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.artifactory.readinessProbe.path }}
            port: 8040
          initialDelaySeconds: {{ .Values.artifactory.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.artifactory.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.artifactory.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.artifactory.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.artifactory.readinessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.artifactory.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.artifactory.livenessProbe.path }}
            port: 8040
          initialDelaySeconds: {{ .Values.artifactory.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.artifactory.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.artifactory.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.artifactory.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.artifactory.livenessProbe.successThreshold }}
        {{- end }}
      {{- $image := .Values.logger.image.repository }}
      {{- $tag := .Values.logger.image.tag }}
      {{- $mountPath := .Values.artifactory.persistence.mountPath }}
      {{- range .Values.artifactory.loggers }}
      - name: {{ . | replace "_" "-" | replace "." "-" }}
        image: '{{ $image }}:{{ $tag }}'
        command:
        - tail
        args:
        - '-F'
        - '{{ $mountPath }}/logs/{{ . }}'
        volumeMounts:
        - name: volume
          mountPath: {{ $mountPath }}
      {{- end }}
      {{ if .Values.artifactory.catalinaLoggers }}
      {{- range .Values.artifactory.catalinaLoggers }}
      - name: {{ . | replace "_" "-" | replace "." "-" }}
        image: '{{ $image }}:{{ $tag }}'
        command:
        - 'sh'
        - '-c'
        - 'sh /scripts/tail-log.sh {{ $mountPath }}/logs/catalina {{ . }}'
        volumeMounts:
        - name: volume
          mountPath: {{ $mountPath }}
        - name: catalina-logger
          mountPath: /scripts/tail-log.sh
          subPath: tail-log.sh
      {{- end }}
      {{- end }}
    {{- if .Values.artifactory.customSidecarContainers }}
{{ tpl .Values.artifactory.customSidecarContainers . | indent 6 }}
    {{- end }}
    {{- with .Values.artifactory.node.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.artifactory.node.affinity }}
    {{- with .Values.artifactory.node.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- else if eq .Values.artifactory.node.podAntiAffinity.type "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: {{ .Values.artifactory.node.podAntiAffinity.topologyKey }}
              labelSelector:
                matchLabels:
                  app: {{ template "artifactory-ha.name" . }}
                  release: {{ .Release.Name }}
                  {{- if eq .Values.artifactory.service.pool "members" }}
                  role: {{ template "artifactory-ha.node.name" . }}
                  {{- end }}
    {{- else if eq .Values.artifactory.node.podAntiAffinity.type "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: {{ .Values.artifactory.node.podAntiAffinity.topologyKey }}
            labelSelector:
              matchLabels:
                app: {{ template "artifactory-ha.name" . }}
                release: {{ .Release.Name }}
                {{- if eq .Values.artifactory.service.pool "members" }}
                role: {{ template "artifactory-ha.node.name" . }}
                {{- end }}
    {{- end }}
    {{- with .Values.artifactory.node.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.artifactory.binarystore.enabled }}
      - name: binarystore-xml
        secret:
          {{- if .Values.artifactory.persistence.customBinarystoreXmlSecret }}
          secretName: {{ .Values.artifactory.persistence.customBinarystoreXmlSecret }}
          {{- else }}
          secretName: {{ template "artifactory-ha.fullname" . }}-binarystore
          {{- end }}
      {{- end }}
      - name: installer-info
        configMap:
          name: {{ template "artifactory-ha.fullname" . }}-installer-info
      {{- if .Values.artifactory.userPluginSecrets }}
      - name: tmp-plugins
        emptyDir: {}
      {{- range .Values.artifactory.userPluginSecrets }}
      - name: {{ tpl . $ }}
        secret:
          secretName: {{ tpl . $ }}
      {{- end }}
      {{- end }}
      {{- if .Values.artifactory.replicator.enabled }}
      - name: replicator-config
        configMap:
          name: {{ template "artifactory-ha.fullname" . }}-replicator-config
      {{- end }}
      {{- if .Values.artifactory.catalinaLoggers }}
      - name: catalina-logger
        configMap:
          name: {{ template "artifactory-ha.fullname" . }}-catalina-logger
      {{- end }}
      {{- if .Values.artifactory.configMaps }}
      - name: artifactory-configmaps
        configMap:
          name: {{ template "artifactory-ha.fullname" . }}-configmaps
      {{- end }}
      {{- if eq .Values.artifactory.persistence.type "file-system" }}
        {{- if .Values.artifactory.persistence.fileSystem.existingSharedClaim.enabled }}
          {{- range $sharedClaimNumber, $e := until (.Values.artifactory.persistence.fileSystem.existingSharedClaim.numberOfExistingClaims|int) }}
      - name: artifactory-ha-data-{{ $sharedClaimNumber }}
        persistentVolumeClaim:
          claimName: {{ template "artifactory-ha.fullname" $ }}-data-pvc-{{ $sharedClaimNumber }}
          {{- end }}
      - name: artifactory-ha-backup
        persistentVolumeClaim:
          claimName: {{ template "artifactory-ha.fullname" $ }}-backup-pvc
        {{- end }}
      {{- end }}
      {{- if eq .Values.artifactory.persistence.type "nfs" }}
      - name: artifactory-ha-data
        persistentVolumeClaim:
          claimName: {{ template "artifactory-ha.fullname" . }}-data-pvc
      - name: artifactory-ha-backup
        persistentVolumeClaim:
          claimName: {{ template "artifactory-ha.fullname" . }}-backup-pvc
      {{- end }}
      - name: systemyaml
        secret:
          secretName: {{ template "artifactory-ha.primary.name" . }}-system-yaml
      {{- if .Values.artifactory.customPersistentVolumeClaim }}
      - name: {{ .Values.artifactory.customPersistentVolumeClaim.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.artifactory.customPersistentVolumeClaim.name }}
      {{- end }}
      {{- if .Values.artifactory.customVolumes }}
{{ tpl .Values.artifactory.customVolumes . | indent 6 }}
      {{- end }}
  {{- if not .Values.artifactory.persistence.enabled }}
      - name: volume
        emptyDir:
          sizeLimit: {{ .Values.artifactory.persistence.size }}
  {{- end }}
  volumeClaimTemplates:
  {{- if .Values.artifactory.persistence.enabled }}
  - metadata:
      name: volume
    {{- if not .Values.artifactory.node.persistence.existingClaim }}
    spec:
      {{- if .Values.artifactory.persistence.storageClassName }}
      {{- if (eq "-" .Values.artifactory.persistence.storageClassName) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.artifactory.persistence.storageClassName }}"
      {{- end }}
      {{- end }}
      accessModes: [ "{{ .Values.artifactory.persistence.accessMode }}" ]
      resources:
        requests:
          storage: {{ .Values.artifactory.persistence.size }}
    {{- end }}
  {{- end }}
  {{- if .Values.artifactory.customPersistentPodVolumeClaim }}
  - metadata:
      name: {{ .Values.artifactory.customPersistentPodVolumeClaim.name }}
    spec:
    {{- if .Values.artifactory.customPersistentPodVolumeClaim.storageClassName }}
      {{- if (eq "-" .Values.artifactory.customPersistentPodVolumeClaim.storageClassName) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.artifactory.customPersistentPodVolumeClaim.storageClassName }}"
      {{- end }}
    {{- end }}
      accessModes:
     {{- range .Values.artifactory.customPersistentPodVolumeClaim.accessModes }}
        - {{ . | quote }}
     {{- end }}
      resources:
        requests:
          storage: {{ .Values.artifactory.customPersistentPodVolumeClaim.size }}
  {{- end }}
